#http://www.apache.org/licenses/LICENSE-2.0.txt
#
#
#Copyright 2015 Intel Corporation
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

#Vagrant::Config.run do |config|
Vagrant.configure("2") do |config|
  config.vm.box = "chef/centos-7.0"
  config.vm.provision :shell, :path => "./script/init.sh"
  # config.vm.forward_port 4567, 4567 # dashboard
  # config.vm.forward_port 5555, 5555, { :protocol => "udp"} # riemann server
  # config.vm.forward_port 5556, 5556 # riemann server: Websocket

  config.vm.network :forwarded_port, {:guest => 4567, :host => 4567, :id => "dashboard", :auto_correct => true}
  config.vm.network :forwarded_port, {:guest => 5555, :host => 5555, :id => "riemann", :auto_correct => true, :protocol => "udp"}
  config.vm.network :forwarded_port, {:guest => 5556, :host => 5556, :id => "riemann_ws", :auto_correct => true}
  # config.vm.network :forwarded_port, {:guest => 1080, :host => 1080, :id => "mailcatcher", :auto_correct => true}


  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "1024"
    v.vmx["numvcpus"] = "2"
  end
  
   config.vm.synced_folder "../../", "/vagrant/go/src/github.com/intelsdi-x/pulse"
end