/*
http://www.apache.org/licenses/LICENSE-2.0.txt


Copyright 2016 Intel Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go.
// source: github.com/intelsdi-x/snap/control/rpc/control.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	github.com/intelsdi-x/snap/control/rpc/control.proto

It has these top-level messages:
	AvailablePluginReply
	AvailablePluginsReply
	PluginReply
	PluginCatalogReply
	MetricReply
	MetricCatalogReply
	GetPluginRequest
	GetPluginReply
	PluginRequest
	FetchMetricsRequest
	GetMetricVersionsRequest
	UnloadPluginRequest
	Time
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/intelsdi-x/snap/internal/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type AvailablePluginReply struct {
	Name             string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Version          int64  `protobuf:"varint,2,opt,name=Version" json:"Version,omitempty"`
	TypeName         string `protobuf:"bytes,3,opt,name=TypeName" json:"TypeName,omitempty"`
	IsSigned         bool   `protobuf:"varint,4,opt,name=IsSigned" json:"IsSigned,omitempty"`
	HitCount         int64  `protobuf:"varint,5,opt,name=HitCount" json:"HitCount,omitempty"`
	ID               uint32 `protobuf:"varint,6,opt,name=ID" json:"ID,omitempty"`
	LastHitTimestamp *Time  `protobuf:"bytes,7,opt,name=LastHitTimestamp" json:"LastHitTimestamp,omitempty"`
}

func (m *AvailablePluginReply) Reset()                    { *m = AvailablePluginReply{} }
func (m *AvailablePluginReply) String() string            { return proto.CompactTextString(m) }
func (*AvailablePluginReply) ProtoMessage()               {}
func (*AvailablePluginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AvailablePluginReply) GetLastHitTimestamp() *Time {
	if m != nil {
		return m.LastHitTimestamp
	}
	return nil
}

type AvailablePluginsReply struct {
	Plugins []*AvailablePluginReply `protobuf:"bytes,1,rep,name=Plugins" json:"Plugins,omitempty"`
}

func (m *AvailablePluginsReply) Reset()                    { *m = AvailablePluginsReply{} }
func (m *AvailablePluginsReply) String() string            { return proto.CompactTextString(m) }
func (*AvailablePluginsReply) ProtoMessage()               {}
func (*AvailablePluginsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AvailablePluginsReply) GetPlugins() []*AvailablePluginReply {
	if m != nil {
		return m.Plugins
	}
	return nil
}

type PluginReply struct {
	Name            string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Version         int64  `protobuf:"varint,2,opt,name=Version" json:"Version,omitempty"`
	TypeName        string `protobuf:"bytes,3,opt,name=TypeName" json:"TypeName,omitempty"`
	IsSigned        bool   `protobuf:"varint,4,opt,name=IsSigned" json:"IsSigned,omitempty"`
	Status          string `protobuf:"bytes,5,opt,name=Status" json:"Status,omitempty"`
	LoadedTimestamp *Time  `protobuf:"bytes,6,opt,name=LoadedTimestamp" json:"LoadedTimestamp,omitempty"`
	ConfigPolicy    []byte `protobuf:"bytes,7,opt,name=ConfigPolicy,proto3" json:"ConfigPolicy,omitempty"`
}

func (m *PluginReply) Reset()                    { *m = PluginReply{} }
func (m *PluginReply) String() string            { return proto.CompactTextString(m) }
func (*PluginReply) ProtoMessage()               {}
func (*PluginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PluginReply) GetLoadedTimestamp() *Time {
	if m != nil {
		return m.LoadedTimestamp
	}
	return nil
}

type PluginCatalogReply struct {
	Plugins []*PluginReply `protobuf:"bytes,1,rep,name=Plugins" json:"Plugins,omitempty"`
}

func (m *PluginCatalogReply) Reset()                    { *m = PluginCatalogReply{} }
func (m *PluginCatalogReply) String() string            { return proto.CompactTextString(m) }
func (*PluginCatalogReply) ProtoMessage()               {}
func (*PluginCatalogReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PluginCatalogReply) GetPlugins() []*PluginReply {
	if m != nil {
		return m.Plugins
	}
	return nil
}

type MetricReply struct {
	Namespace          []string `protobuf:"bytes,1,rep,name=Namespace" json:"Namespace,omitempty"`
	Version            int64    `protobuf:"varint,2,opt,name=Version" json:"Version,omitempty"`
	LastAdvertisedTime *Time    `protobuf:"bytes,3,opt,name=LastAdvertisedTime" json:"LastAdvertisedTime,omitempty"`
	ConfigPolicy       []byte   `protobuf:"bytes,4,opt,name=ConfigPolicy,proto3" json:"ConfigPolicy,omitempty"`
}

func (m *MetricReply) Reset()                    { *m = MetricReply{} }
func (m *MetricReply) String() string            { return proto.CompactTextString(m) }
func (*MetricReply) ProtoMessage()               {}
func (*MetricReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MetricReply) GetLastAdvertisedTime() *Time {
	if m != nil {
		return m.LastAdvertisedTime
	}
	return nil
}

type MetricCatalogReply struct {
	Metrics []*MetricReply `protobuf:"bytes,1,rep,name=Metrics" json:"Metrics,omitempty"`
}

func (m *MetricCatalogReply) Reset()                    { *m = MetricCatalogReply{} }
func (m *MetricCatalogReply) String() string            { return proto.CompactTextString(m) }
func (*MetricCatalogReply) ProtoMessage()               {}
func (*MetricCatalogReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MetricCatalogReply) GetMetrics() []*MetricReply {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type GetPluginRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Version  int32  `protobuf:"varint,2,opt,name=Version" json:"Version,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=Type" json:"Type,omitempty"`
	Download bool   `protobuf:"varint,4,opt,name=Download" json:"Download,omitempty"`
}

func (m *GetPluginRequest) Reset()                    { *m = GetPluginRequest{} }
func (m *GetPluginRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPluginRequest) ProtoMessage()               {}
func (*GetPluginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type GetPluginReply struct {
	Plugin      *PluginReply `protobuf:"bytes,1,opt,name=Plugin" json:"Plugin,omitempty"`
	PluginBytes []byte       `protobuf:"bytes,2,opt,name=PluginBytes,proto3" json:"PluginBytes,omitempty"`
}

func (m *GetPluginReply) Reset()                    { *m = GetPluginReply{} }
func (m *GetPluginReply) String() string            { return proto.CompactTextString(m) }
func (*GetPluginReply) ProtoMessage()               {}
func (*GetPluginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetPluginReply) GetPlugin() *PluginReply {
	if m != nil {
		return m.Plugin
	}
	return nil
}

type PluginRequest struct {
	Name       string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	CheckSum   []byte `protobuf:"bytes,2,opt,name=CheckSum,proto3" json:"CheckSum,omitempty"`
	Signature  []byte `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	PluginFile []byte `protobuf:"bytes,4,opt,name=PluginFile,proto3" json:"PluginFile,omitempty"`
}

func (m *PluginRequest) Reset()                    { *m = PluginRequest{} }
func (m *PluginRequest) String() string            { return proto.CompactTextString(m) }
func (*PluginRequest) ProtoMessage()               {}
func (*PluginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type FetchMetricsRequest struct {
	Namespace []string `protobuf:"bytes,1,rep,name=Namespace" json:"Namespace,omitempty"`
	Version   int32    `protobuf:"varint,2,opt,name=Version" json:"Version,omitempty"`
}

func (m *FetchMetricsRequest) Reset()                    { *m = FetchMetricsRequest{} }
func (m *FetchMetricsRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchMetricsRequest) ProtoMessage()               {}
func (*FetchMetricsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type GetMetricVersionsRequest struct {
	Namespace []string `protobuf:"bytes,1,rep,name=Namespace" json:"Namespace,omitempty"`
}

func (m *GetMetricVersionsRequest) Reset()                    { *m = GetMetricVersionsRequest{} }
func (m *GetMetricVersionsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetMetricVersionsRequest) ProtoMessage()               {}
func (*GetMetricVersionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type UnloadPluginRequest struct {
	Name       string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Version    int32  `protobuf:"varint,2,opt,name=Version" json:"Version,omitempty"`
	PluginType string `protobuf:"bytes,3,opt,name=PluginType" json:"PluginType,omitempty"`
}

func (m *UnloadPluginRequest) Reset()                    { *m = UnloadPluginRequest{} }
func (m *UnloadPluginRequest) String() string            { return proto.CompactTextString(m) }
func (*UnloadPluginRequest) ProtoMessage()               {}
func (*UnloadPluginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type Time struct {
	Sec  int64 `protobuf:"varint,1,opt,name=Sec" json:"Sec,omitempty"`
	Nsec int64 `protobuf:"varint,2,opt,name=Nsec" json:"Nsec,omitempty"`
}

func (m *Time) Reset()                    { *m = Time{} }
func (m *Time) String() string            { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()               {}
func (*Time) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func init() {
	proto.RegisterType((*AvailablePluginReply)(nil), "rpc.AvailablePluginReply")
	proto.RegisterType((*AvailablePluginsReply)(nil), "rpc.AvailablePluginsReply")
	proto.RegisterType((*PluginReply)(nil), "rpc.PluginReply")
	proto.RegisterType((*PluginCatalogReply)(nil), "rpc.PluginCatalogReply")
	proto.RegisterType((*MetricReply)(nil), "rpc.MetricReply")
	proto.RegisterType((*MetricCatalogReply)(nil), "rpc.MetricCatalogReply")
	proto.RegisterType((*GetPluginRequest)(nil), "rpc.GetPluginRequest")
	proto.RegisterType((*GetPluginReply)(nil), "rpc.GetPluginReply")
	proto.RegisterType((*PluginRequest)(nil), "rpc.PluginRequest")
	proto.RegisterType((*FetchMetricsRequest)(nil), "rpc.FetchMetricsRequest")
	proto.RegisterType((*GetMetricVersionsRequest)(nil), "rpc.GetMetricVersionsRequest")
	proto.RegisterType((*UnloadPluginRequest)(nil), "rpc.UnloadPluginRequest")
	proto.RegisterType((*Time)(nil), "rpc.Time")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for MetricManager service

type MetricManagerClient interface {
	Load(ctx context.Context, in *PluginRequest, opts ...grpc.CallOption) (*PluginReply, error)
	MetricCatalog(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*MetricCatalogReply, error)
	FetchMetrics(ctx context.Context, in *FetchMetricsRequest, opts ...grpc.CallOption) (*MetricCatalogReply, error)
	GetMetricVersions(ctx context.Context, in *GetMetricVersionsRequest, opts ...grpc.CallOption) (*MetricCatalogReply, error)
	GetMetric(ctx context.Context, in *FetchMetricsRequest, opts ...grpc.CallOption) (*MetricReply, error)
	Unload(ctx context.Context, in *UnloadPluginRequest, opts ...grpc.CallOption) (*PluginReply, error)
	PluginCatalog(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*PluginCatalogReply, error)
	AvailablePlugins(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AvailablePluginsReply, error)
	GetPlugin(ctx context.Context, in *GetPluginRequest, opts ...grpc.CallOption) (*GetPluginReply, error)
}

type metricManagerClient struct {
	cc *grpc.ClientConn
}

func NewMetricManagerClient(cc *grpc.ClientConn) MetricManagerClient {
	return &metricManagerClient{cc}
}

func (c *metricManagerClient) Load(ctx context.Context, in *PluginRequest, opts ...grpc.CallOption) (*PluginReply, error) {
	out := new(PluginReply)
	err := grpc.Invoke(ctx, "/rpc.MetricManager/Load", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricManagerClient) MetricCatalog(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*MetricCatalogReply, error) {
	out := new(MetricCatalogReply)
	err := grpc.Invoke(ctx, "/rpc.MetricManager/MetricCatalog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricManagerClient) FetchMetrics(ctx context.Context, in *FetchMetricsRequest, opts ...grpc.CallOption) (*MetricCatalogReply, error) {
	out := new(MetricCatalogReply)
	err := grpc.Invoke(ctx, "/rpc.MetricManager/FetchMetrics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricManagerClient) GetMetricVersions(ctx context.Context, in *GetMetricVersionsRequest, opts ...grpc.CallOption) (*MetricCatalogReply, error) {
	out := new(MetricCatalogReply)
	err := grpc.Invoke(ctx, "/rpc.MetricManager/GetMetricVersions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricManagerClient) GetMetric(ctx context.Context, in *FetchMetricsRequest, opts ...grpc.CallOption) (*MetricReply, error) {
	out := new(MetricReply)
	err := grpc.Invoke(ctx, "/rpc.MetricManager/GetMetric", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricManagerClient) Unload(ctx context.Context, in *UnloadPluginRequest, opts ...grpc.CallOption) (*PluginReply, error) {
	out := new(PluginReply)
	err := grpc.Invoke(ctx, "/rpc.MetricManager/Unload", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricManagerClient) PluginCatalog(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*PluginCatalogReply, error) {
	out := new(PluginCatalogReply)
	err := grpc.Invoke(ctx, "/rpc.MetricManager/PluginCatalog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricManagerClient) AvailablePlugins(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AvailablePluginsReply, error) {
	out := new(AvailablePluginsReply)
	err := grpc.Invoke(ctx, "/rpc.MetricManager/AvailablePlugins", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricManagerClient) GetPlugin(ctx context.Context, in *GetPluginRequest, opts ...grpc.CallOption) (*GetPluginReply, error) {
	out := new(GetPluginReply)
	err := grpc.Invoke(ctx, "/rpc.MetricManager/GetPlugin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MetricManager service

type MetricManagerServer interface {
	Load(context.Context, *PluginRequest) (*PluginReply, error)
	MetricCatalog(context.Context, *common.Empty) (*MetricCatalogReply, error)
	FetchMetrics(context.Context, *FetchMetricsRequest) (*MetricCatalogReply, error)
	GetMetricVersions(context.Context, *GetMetricVersionsRequest) (*MetricCatalogReply, error)
	GetMetric(context.Context, *FetchMetricsRequest) (*MetricReply, error)
	Unload(context.Context, *UnloadPluginRequest) (*PluginReply, error)
	PluginCatalog(context.Context, *common.Empty) (*PluginCatalogReply, error)
	AvailablePlugins(context.Context, *common.Empty) (*AvailablePluginsReply, error)
	GetPlugin(context.Context, *GetPluginRequest) (*GetPluginReply, error)
}

func RegisterMetricManagerServer(s *grpc.Server, srv MetricManagerServer) {
	s.RegisterService(&_MetricManager_serviceDesc, srv)
}

func _MetricManager_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(PluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MetricManagerServer).Load(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _MetricManager_MetricCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MetricManagerServer).MetricCatalog(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _MetricManager_FetchMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(FetchMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MetricManagerServer).FetchMetrics(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _MetricManager_GetMetricVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetMetricVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MetricManagerServer).GetMetricVersions(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _MetricManager_GetMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(FetchMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MetricManagerServer).GetMetric(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _MetricManager_Unload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(UnloadPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MetricManagerServer).Unload(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _MetricManager_PluginCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MetricManagerServer).PluginCatalog(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _MetricManager_AvailablePlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MetricManagerServer).AvailablePlugins(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _MetricManager_GetPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MetricManagerServer).GetPlugin(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _MetricManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.MetricManager",
	HandlerType: (*MetricManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Load",
			Handler:    _MetricManager_Load_Handler,
		},
		{
			MethodName: "MetricCatalog",
			Handler:    _MetricManager_MetricCatalog_Handler,
		},
		{
			MethodName: "FetchMetrics",
			Handler:    _MetricManager_FetchMetrics_Handler,
		},
		{
			MethodName: "GetMetricVersions",
			Handler:    _MetricManager_GetMetricVersions_Handler,
		},
		{
			MethodName: "GetMetric",
			Handler:    _MetricManager_GetMetric_Handler,
		},
		{
			MethodName: "Unload",
			Handler:    _MetricManager_Unload_Handler,
		},
		{
			MethodName: "PluginCatalog",
			Handler:    _MetricManager_PluginCatalog_Handler,
		},
		{
			MethodName: "AvailablePlugins",
			Handler:    _MetricManager_AvailablePlugins_Handler,
		},
		{
			MethodName: "GetPlugin",
			Handler:    _MetricManager_GetPlugin_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 775 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x55, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x3e, 0x69, 0x5c, 0x27, 0x9e, 0x26, 0x6d, 0xce, 0xf6, 0xf4, 0x60, 0x22, 0x40, 0x95, 0xaf,
	0x2a, 0x04, 0x89, 0xd4, 0xf2, 0xd7, 0x2b, 0x28, 0x29, 0x85, 0x4a, 0x0d, 0xaa, 0x9c, 0xc2, 0x15,
	0x37, 0xae, 0xb3, 0x24, 0x2b, 0xfc, 0x87, 0x77, 0x53, 0xc8, 0x05, 0x6f, 0xc3, 0x43, 0xf0, 0x36,
	0xdc, 0xf0, 0x20, 0xec, 0x9f, 0x9b, 0xd8, 0x71, 0x43, 0x11, 0x12, 0x57, 0xf6, 0xcc, 0xce, 0xcc,
	0xce, 0xf7, 0x7d, 0xb3, 0xbb, 0xf0, 0x60, 0x44, 0xd8, 0x78, 0x72, 0xde, 0xf1, 0xe3, 0xb0, 0x4b,
	0x22, 0x86, 0x03, 0x3a, 0x24, 0xf7, 0x3f, 0x77, 0x69, 0xe4, 0x25, 0x5d, 0x3f, 0x8e, 0x58, 0x1a,
	0x07, 0xdd, 0x34, 0xf1, 0xb3, 0xff, 0x4e, 0x92, 0xc6, 0x2c, 0x46, 0x55, 0xee, 0x6a, 0x3f, 0x5e,
	0x92, 0x2a, 0xec, 0x34, 0xf2, 0x02, 0x9e, 0x17, 0x86, 0x71, 0xa4, 0x3f, 0x2a, 0xdb, 0xf9, 0x5e,
	0x81, 0xff, 0x0e, 0x2e, 0x3c, 0x12, 0x78, 0xe7, 0x01, 0x3e, 0x0d, 0x26, 0x23, 0x12, 0xb9, 0x38,
	0x09, 0xa6, 0x08, 0x81, 0xf1, 0xda, 0x0b, 0xb1, 0x5d, 0xd9, 0xae, 0xec, 0x58, 0xae, 0x11, 0xf1,
	0x7f, 0x64, 0x43, 0xed, 0x2d, 0x4e, 0x29, 0x89, 0x23, 0x7b, 0x85, 0xbb, 0xab, 0x6e, 0xed, 0x42,
	0x99, 0xa8, 0x0d, 0xf5, 0xb3, 0x69, 0x82, 0x65, 0x46, 0x55, 0x66, 0xd4, 0x99, 0xb6, 0xc5, 0xda,
	0x31, 0x1d, 0x90, 0x51, 0x84, 0x87, 0xb6, 0xc1, 0xd7, 0xea, 0x6e, 0x9d, 0x68, 0x5b, 0xac, 0xbd,
	0x22, 0xac, 0x17, 0x4f, 0x22, 0x66, 0xaf, 0xca, 0x92, 0xf5, 0xb1, 0xb6, 0xd1, 0x3a, 0xac, 0x1c,
	0x1f, 0xda, 0x26, 0xf7, 0x36, 0xdd, 0x15, 0x72, 0x88, 0x1e, 0x42, 0xeb, 0xc4, 0xa3, 0x8c, 0xc7,
	0x9f, 0x91, 0x10, 0x53, 0xe6, 0x85, 0x89, 0x5d, 0xe3, 0xab, 0x6b, 0xbb, 0x56, 0x87, 0x73, 0xd0,
	0x11, 0x5e, 0xb7, 0x15, 0x14, 0x42, 0x9c, 0x13, 0xd8, 0x2a, 0x00, 0xa4, 0x0a, 0xe1, 0x1e, 0xd4,
	0xb4, 0xcd, 0x41, 0x56, 0x79, 0x99, 0x9b, 0xb2, 0x4c, 0x19, 0x1b, 0x6e, 0x2d, 0x51, 0x91, 0xce,
	0x8f, 0x0a, 0xac, 0xfd, 0x7d, 0x9a, 0xfe, 0x07, 0x73, 0xc0, 0x3c, 0x36, 0xa1, 0x92, 0x24, 0xcb,
	0x35, 0xa9, 0xb4, 0x38, 0x84, 0x8d, 0x93, 0xd8, 0x1b, 0xe2, 0xe1, 0x8c, 0x11, 0xb3, 0xc8, 0xc8,
	0x46, 0x90, 0x8f, 0x40, 0x0e, 0x34, 0x7a, 0x71, 0xf4, 0x9e, 0x8c, 0x4e, 0xe3, 0x80, 0xf8, 0x53,
	0xc9, 0x61, 0xc3, 0x6d, 0xf8, 0x73, 0x3e, 0xe7, 0x19, 0x20, 0x85, 0xb2, 0xe7, 0x31, 0x2f, 0x88,
	0x47, 0x0a, 0xec, 0xdd, 0x22, 0x63, 0x2d, 0xb9, 0x4d, 0x29, 0x51, 0x5f, 0x39, 0x51, 0x7d, 0xcc,
	0x52, 0xe2, 0xab, 0xdc, 0x5b, 0x60, 0x09, 0x98, 0x34, 0xf1, 0x7c, 0x2c, 0xb3, 0x2d, 0xd7, 0x8a,
	0x32, 0xc7, 0x12, 0xca, 0xf6, 0x01, 0x09, 0xd5, 0x0f, 0x86, 0xdc, 0xc1, 0x08, 0x55, 0x40, 0x24,
	0x79, 0x39, 0x94, 0x28, 0x58, 0x08, 0x5a, 0x00, 0x6a, 0x94, 0x03, 0x55, 0x5d, 0x16, 0x81, 0x2a,
	0x6f, 0x1e, 0xe8, 0x1c, 0x1e, 0xb7, 0x16, 0xaa, 0x00, 0x27, 0x81, 0xd6, 0x4b, 0xcc, 0x32, 0x0e,
	0x3e, 0x4e, 0x38, 0xcb, 0xd7, 0x99, 0x8a, 0xd5, 0x19, 0x44, 0x1e, 0x2d, 0xa6, 0x42, 0x4f, 0x84,
	0x21, 0x26, 0x42, 0x4c, 0xc3, 0x61, 0xfc, 0x29, 0x12, 0xda, 0x65, 0xd3, 0x30, 0xd4, 0xb6, 0xf3,
	0x0e, 0xd6, 0xe7, 0x76, 0x14, 0xfd, 0xee, 0x80, 0xa9, 0x4c, 0xb9, 0x63, 0x99, 0x2e, 0xa6, 0xd2,
	0x05, 0x6d, 0x67, 0xe3, 0xfb, 0x7c, 0xca, 0x30, 0x95, 0x9d, 0x34, 0xdc, 0xb5, 0x64, 0xe6, 0x72,
	0xbe, 0x40, 0xf3, 0xd7, 0x60, 0x78, 0x7b, 0xbd, 0x31, 0xf6, 0x3f, 0x0c, 0x26, 0xa1, 0xae, 0x51,
	0xf7, 0xb5, 0x2d, 0x94, 0x16, 0x63, 0xcb, 0x07, 0x34, 0x55, 0x98, 0x1a, 0xae, 0x45, 0x33, 0x07,
	0xba, 0x03, 0xa0, 0xca, 0x1f, 0x91, 0x00, 0x6b, 0x49, 0x20, 0xb9, 0xf4, 0x38, 0x7d, 0xd8, 0x3c,
	0xc2, 0xcc, 0x1f, 0x6b, 0xfe, 0xb3, 0x26, 0x7e, 0x6b, 0x7c, 0x66, 0xdc, 0x3a, 0x4f, 0xc0, 0xe6,
	0x5c, 0xa9, 0x62, 0x3a, 0xe4, 0x7a, 0x35, 0x1d, 0x1f, 0x36, 0xdf, 0x48, 0xbe, 0xff, 0x44, 0xda,
	0x4b, 0xb4, 0x73, 0x02, 0x6b, 0xb4, 0xc2, 0xe3, 0xdc, 0xe3, 0xd2, 0x8b, 0x51, 0x6d, 0x41, 0x75,
	0x80, 0x7d, 0x59, 0xb4, 0xea, 0x56, 0x29, 0xf6, 0xe5, 0x3e, 0xfc, 0xab, 0x8f, 0x83, 0x11, 0xf1,
	0xff, 0xdd, 0x6f, 0x06, 0x34, 0x15, 0x94, 0xbe, 0x17, 0x79, 0x23, 0x9c, 0xa2, 0x0e, 0x18, 0xe2,
	0x02, 0x40, 0x28, 0x27, 0xb8, 0xec, 0xb4, 0xbd, 0x30, 0x04, 0xce, 0x3f, 0xfc, 0x34, 0x35, 0x73,
	0xe3, 0x8e, 0x9a, 0x1d, 0xfd, 0x1c, 0xbc, 0x08, 0x13, 0x36, 0x6d, 0xdf, 0x98, 0x9b, 0xf3, 0xf9,
	0x13, 0xc1, 0x53, 0x7b, 0xd0, 0x98, 0x17, 0x06, 0xd9, 0x32, 0xb4, 0x44, 0xab, 0x65, 0x45, 0xfa,
	0xf0, 0xef, 0x82, 0x1c, 0xe8, 0xb6, 0x8c, 0xbf, 0x4a, 0xa6, 0x65, 0xe5, 0xf6, 0xc1, 0xba, 0x4c,
	0x5b, 0xd2, 0xd0, 0xc2, 0xe9, 0xe5, 0xa9, 0x8f, 0xc0, 0x54, 0xf2, 0xea, 0xbc, 0x12, 0xad, 0xaf,
	0x62, 0x30, 0x77, 0x33, 0x96, 0x33, 0xb8, 0x78, 0x79, 0xf2, 0xd4, 0xa7, 0xd0, 0x2a, 0xbe, 0x44,
	0xc5, 0xec, 0x76, 0xd9, 0x13, 0x44, 0xf3, 0x70, 0x95, 0x13, 0x6d, 0x65, 0xac, 0xe5, 0x7b, 0xde,
	0x2c, 0xba, 0x65, 0xea, 0xb9, 0x29, 0x9f, 0xfb, 0xbd, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa1,
	0x91, 0x8c, 0x78, 0x64, 0x08, 0x00, 0x00,
}
