/*
http://www.apache.org/licenses/LICENSE-2.0.txt


Copyright 2016 Intel Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go.
// source: github.com/intelsdi-x/snap/control/plugin/rpc/plugin.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	github.com/intelsdi-x/snap/control/plugin/rpc/plugin.proto

It has these top-level messages:
	Rule
	SetKeyArg
	SetKeyReply
	PingReply
	KillRequest
	KillReply
	GetConfigPolicyReply
	BoolRule
	BoolPolicy
	FloatRule
	FloatPolicy
	IntegerRule
	IntegerPolicy
	StringRule
	StringPolicy
	CollectMetricsArg
	CollectMetricsReply
	GetMetricTypesArg
	GetMetricTypesReply
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/intelsdi-x/snap/grpc/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Rule struct {
	RuleType      string  `protobuf:"bytes,1,opt,name=rule_type" json:"rule_type,omitempty"`
	Key           string  `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Required      bool    `protobuf:"varint,3,opt,name=required" json:"required,omitempty"`
	Eescription   string  `protobuf:"bytes,4,opt,name=eescription" json:"eescription,omitempty"`
	BoolDefault   bool    `protobuf:"varint,5,opt,name=bool_default" json:"bool_default,omitempty"`
	FloatDefault  float64 `protobuf:"fixed64,6,opt,name=float_default" json:"float_default,omitempty"`
	FloatMinimum  float64 `protobuf:"fixed64,7,opt,name=float_minimum" json:"float_minimum,omitempty"`
	FloatMaximum  float64 `protobuf:"fixed64,8,opt,name=float_maximum" json:"float_maximum,omitempty"`
	IntDefault    int64   `protobuf:"varint,9,opt,name=int_default" json:"int_default,omitempty"`
	IntMinimum    int64   `protobuf:"varint,10,opt,name=int_minimum" json:"int_minimum,omitempty"`
	IntMaximum    int64   `protobuf:"varint,11,opt,name=int_maximum" json:"int_maximum,omitempty"`
	StringDefault string  `protobuf:"bytes,12,opt,name=string_default" json:"string_default,omitempty"`
}

func (m *Rule) Reset()                    { *m = Rule{} }
func (m *Rule) String() string            { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()               {}
func (*Rule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SetKeyArg struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *SetKeyArg) Reset()                    { *m = SetKeyArg{} }
func (m *SetKeyArg) String() string            { return proto.CompactTextString(m) }
func (*SetKeyArg) ProtoMessage()               {}
func (*SetKeyArg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SetKeyReply struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *SetKeyReply) Reset()                    { *m = SetKeyReply{} }
func (m *SetKeyReply) String() string            { return proto.CompactTextString(m) }
func (*SetKeyReply) ProtoMessage()               {}
func (*SetKeyReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PingReply struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *PingReply) Reset()                    { *m = PingReply{} }
func (m *PingReply) String() string            { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()               {}
func (*PingReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type KillRequest struct {
	Reason string `protobuf:"bytes,1,opt,name=Reason" json:"Reason,omitempty"`
}

func (m *KillRequest) Reset()                    { *m = KillRequest{} }
func (m *KillRequest) String() string            { return proto.CompactTextString(m) }
func (*KillRequest) ProtoMessage()               {}
func (*KillRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type KillReply struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *KillReply) Reset()                    { *m = KillReply{} }
func (m *KillReply) String() string            { return proto.CompactTextString(m) }
func (*KillReply) ProtoMessage()               {}
func (*KillReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type GetConfigPolicyReply struct {
	Error         string                    `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	BoolPolicy    map[string]*BoolPolicy    `protobuf:"bytes,2,rep,name=bool_policy" json:"bool_policy,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FloatPolicy   map[string]*FloatPolicy   `protobuf:"bytes,3,rep,name=float_policy" json:"float_policy,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IntegerPolicy map[string]*IntegerPolicy `protobuf:"bytes,4,rep,name=integer_policy" json:"integer_policy,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringPolicy  map[string]*StringPolicy  `protobuf:"bytes,5,rep,name=string_policy" json:"string_policy,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GetConfigPolicyReply) Reset()                    { *m = GetConfigPolicyReply{} }
func (m *GetConfigPolicyReply) String() string            { return proto.CompactTextString(m) }
func (*GetConfigPolicyReply) ProtoMessage()               {}
func (*GetConfigPolicyReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetConfigPolicyReply) GetBoolPolicy() map[string]*BoolPolicy {
	if m != nil {
		return m.BoolPolicy
	}
	return nil
}

func (m *GetConfigPolicyReply) GetFloatPolicy() map[string]*FloatPolicy {
	if m != nil {
		return m.FloatPolicy
	}
	return nil
}

func (m *GetConfigPolicyReply) GetIntegerPolicy() map[string]*IntegerPolicy {
	if m != nil {
		return m.IntegerPolicy
	}
	return nil
}

func (m *GetConfigPolicyReply) GetStringPolicy() map[string]*StringPolicy {
	if m != nil {
		return m.StringPolicy
	}
	return nil
}

type BoolRule struct {
	Required bool `protobuf:"varint,1,opt,name=required" json:"required,omitempty"`
	Default  bool `protobuf:"varint,2,opt,name=default" json:"default,omitempty"`
}

func (m *BoolRule) Reset()                    { *m = BoolRule{} }
func (m *BoolRule) String() string            { return proto.CompactTextString(m) }
func (*BoolRule) ProtoMessage()               {}
func (*BoolRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type BoolPolicy struct {
	Rules map[string]*BoolRule `protobuf:"bytes,1,rep,name=rules" json:"rules,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *BoolPolicy) Reset()                    { *m = BoolPolicy{} }
func (m *BoolPolicy) String() string            { return proto.CompactTextString(m) }
func (*BoolPolicy) ProtoMessage()               {}
func (*BoolPolicy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BoolPolicy) GetRules() map[string]*BoolRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

type FloatRule struct {
	Required bool    `protobuf:"varint,1,opt,name=required" json:"required,omitempty"`
	Minimum  float64 `protobuf:"fixed64,2,opt,name=minimum" json:"minimum,omitempty"`
	Maximum  float64 `protobuf:"fixed64,3,opt,name=maximum" json:"maximum,omitempty"`
	Default  float64 `protobuf:"fixed64,4,opt,name=default" json:"default,omitempty"`
}

func (m *FloatRule) Reset()                    { *m = FloatRule{} }
func (m *FloatRule) String() string            { return proto.CompactTextString(m) }
func (*FloatRule) ProtoMessage()               {}
func (*FloatRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type FloatPolicy struct {
	Rules map[string]*FloatRule `protobuf:"bytes,1,rep,name=rules" json:"rules,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *FloatPolicy) Reset()                    { *m = FloatPolicy{} }
func (m *FloatPolicy) String() string            { return proto.CompactTextString(m) }
func (*FloatPolicy) ProtoMessage()               {}
func (*FloatPolicy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *FloatPolicy) GetRules() map[string]*FloatRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

type IntegerRule struct {
	Required bool  `protobuf:"varint,1,opt,name=required" json:"required,omitempty"`
	Minimum  int64 `protobuf:"varint,2,opt,name=minimum" json:"minimum,omitempty"`
	Maximum  int64 `protobuf:"varint,3,opt,name=maximum" json:"maximum,omitempty"`
	Default  int64 `protobuf:"varint,4,opt,name=default" json:"default,omitempty"`
}

func (m *IntegerRule) Reset()                    { *m = IntegerRule{} }
func (m *IntegerRule) String() string            { return proto.CompactTextString(m) }
func (*IntegerRule) ProtoMessage()               {}
func (*IntegerRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type IntegerPolicy struct {
	Rules map[string]*IntegerRule `protobuf:"bytes,1,rep,name=rules" json:"rules,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *IntegerPolicy) Reset()                    { *m = IntegerPolicy{} }
func (m *IntegerPolicy) String() string            { return proto.CompactTextString(m) }
func (*IntegerPolicy) ProtoMessage()               {}
func (*IntegerPolicy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *IntegerPolicy) GetRules() map[string]*IntegerRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

type StringRule struct {
	Required bool   `protobuf:"varint,1,opt,name=required" json:"required,omitempty"`
	Default  string `protobuf:"bytes,2,opt,name=default" json:"default,omitempty"`
}

func (m *StringRule) Reset()                    { *m = StringRule{} }
func (m *StringRule) String() string            { return proto.CompactTextString(m) }
func (*StringRule) ProtoMessage()               {}
func (*StringRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type StringPolicy struct {
	Rules map[string]*StringRule `protobuf:"bytes,1,rep,name=rules" json:"rules,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *StringPolicy) Reset()                    { *m = StringPolicy{} }
func (m *StringPolicy) String() string            { return proto.CompactTextString(m) }
func (*StringPolicy) ProtoMessage()               {}
func (*StringPolicy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *StringPolicy) GetRules() map[string]*StringRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

type CollectMetricsArg struct {
	Metrics []*common.Metric `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty"`
}

func (m *CollectMetricsArg) Reset()                    { *m = CollectMetricsArg{} }
func (m *CollectMetricsArg) String() string            { return proto.CompactTextString(m) }
func (*CollectMetricsArg) ProtoMessage()               {}
func (*CollectMetricsArg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CollectMetricsArg) GetMetrics() []*common.Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type CollectMetricsReply struct {
	Metrics []*common.Metric `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty"`
	Error   string           `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *CollectMetricsReply) Reset()                    { *m = CollectMetricsReply{} }
func (m *CollectMetricsReply) String() string            { return proto.CompactTextString(m) }
func (*CollectMetricsReply) ProtoMessage()               {}
func (*CollectMetricsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *CollectMetricsReply) GetMetrics() []*common.Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type GetMetricTypesArg struct {
	Config *common.ConfigMap `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
}

func (m *GetMetricTypesArg) Reset()                    { *m = GetMetricTypesArg{} }
func (m *GetMetricTypesArg) String() string            { return proto.CompactTextString(m) }
func (*GetMetricTypesArg) ProtoMessage()               {}
func (*GetMetricTypesArg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetMetricTypesArg) GetConfig() *common.ConfigMap {
	if m != nil {
		return m.Config
	}
	return nil
}

type GetMetricTypesReply struct {
	Metrics []*common.Metric `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty"`
	Error   string           `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GetMetricTypesReply) Reset()                    { *m = GetMetricTypesReply{} }
func (m *GetMetricTypesReply) String() string            { return proto.CompactTextString(m) }
func (*GetMetricTypesReply) ProtoMessage()               {}
func (*GetMetricTypesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *GetMetricTypesReply) GetMetrics() []*common.Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func init() {
	proto.RegisterType((*Rule)(nil), "rpc.Rule")
	proto.RegisterType((*SetKeyArg)(nil), "rpc.SetKeyArg")
	proto.RegisterType((*SetKeyReply)(nil), "rpc.SetKeyReply")
	proto.RegisterType((*PingReply)(nil), "rpc.PingReply")
	proto.RegisterType((*KillRequest)(nil), "rpc.KillRequest")
	proto.RegisterType((*KillReply)(nil), "rpc.KillReply")
	proto.RegisterType((*GetConfigPolicyReply)(nil), "rpc.GetConfigPolicyReply")
	proto.RegisterType((*BoolRule)(nil), "rpc.BoolRule")
	proto.RegisterType((*BoolPolicy)(nil), "rpc.BoolPolicy")
	proto.RegisterType((*FloatRule)(nil), "rpc.FloatRule")
	proto.RegisterType((*FloatPolicy)(nil), "rpc.FloatPolicy")
	proto.RegisterType((*IntegerRule)(nil), "rpc.IntegerRule")
	proto.RegisterType((*IntegerPolicy)(nil), "rpc.IntegerPolicy")
	proto.RegisterType((*StringRule)(nil), "rpc.StringRule")
	proto.RegisterType((*StringPolicy)(nil), "rpc.StringPolicy")
	proto.RegisterType((*CollectMetricsArg)(nil), "rpc.CollectMetricsArg")
	proto.RegisterType((*CollectMetricsReply)(nil), "rpc.CollectMetricsReply")
	proto.RegisterType((*GetMetricTypesArg)(nil), "rpc.GetMetricTypesArg")
	proto.RegisterType((*GetMetricTypesReply)(nil), "rpc.GetMetricTypesReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Collector service

type CollectorClient interface {
	SetKey(ctx context.Context, in *SetKeyArg, opts ...grpc.CallOption) (*SetKeyReply, error)
	Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*PingReply, error)
	Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillReply, error)
	GetConfigPolicy(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*GetConfigPolicyReply, error)
	CollectMetrics(ctx context.Context, in *CollectMetricsArg, opts ...grpc.CallOption) (*CollectMetricsReply, error)
	GetMetricTypes(ctx context.Context, in *GetMetricTypesArg, opts ...grpc.CallOption) (*GetMetricTypesReply, error)
}

type collectorClient struct {
	cc *grpc.ClientConn
}

func NewCollectorClient(cc *grpc.ClientConn) CollectorClient {
	return &collectorClient{cc}
}

func (c *collectorClient) SetKey(ctx context.Context, in *SetKeyArg, opts ...grpc.CallOption) (*SetKeyReply, error) {
	out := new(SetKeyReply)
	err := grpc.Invoke(ctx, "/rpc.Collector/SetKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorClient) Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := grpc.Invoke(ctx, "/rpc.Collector/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorClient) Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillReply, error) {
	out := new(KillReply)
	err := grpc.Invoke(ctx, "/rpc.Collector/Kill", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorClient) GetConfigPolicy(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*GetConfigPolicyReply, error) {
	out := new(GetConfigPolicyReply)
	err := grpc.Invoke(ctx, "/rpc.Collector/GetConfigPolicy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorClient) CollectMetrics(ctx context.Context, in *CollectMetricsArg, opts ...grpc.CallOption) (*CollectMetricsReply, error) {
	out := new(CollectMetricsReply)
	err := grpc.Invoke(ctx, "/rpc.Collector/CollectMetrics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorClient) GetMetricTypes(ctx context.Context, in *GetMetricTypesArg, opts ...grpc.CallOption) (*GetMetricTypesReply, error) {
	out := new(GetMetricTypesReply)
	err := grpc.Invoke(ctx, "/rpc.Collector/GetMetricTypes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Collector service

type CollectorServer interface {
	SetKey(context.Context, *SetKeyArg) (*SetKeyReply, error)
	Ping(context.Context, *common.Empty) (*PingReply, error)
	Kill(context.Context, *KillRequest) (*KillReply, error)
	GetConfigPolicy(context.Context, *common.Empty) (*GetConfigPolicyReply, error)
	CollectMetrics(context.Context, *CollectMetricsArg) (*CollectMetricsReply, error)
	GetMetricTypes(context.Context, *GetMetricTypesArg) (*GetMetricTypesReply, error)
}

func RegisterCollectorServer(s *grpc.Server, srv CollectorServer) {
	s.RegisterService(&_Collector_serviceDesc, srv)
}

func _Collector_SetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetKeyArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).SetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Collector/SetKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).SetKey(ctx, req.(*SetKeyArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collector_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Collector/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).Ping(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collector_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Collector/Kill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).Kill(ctx, req.(*KillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collector_GetConfigPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).GetConfigPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Collector/GetConfigPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).GetConfigPolicy(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collector_CollectMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectMetricsArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).CollectMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Collector/CollectMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).CollectMetrics(ctx, req.(*CollectMetricsArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collector_GetMetricTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricTypesArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).GetMetricTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Collector/GetMetricTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).GetMetricTypes(ctx, req.(*GetMetricTypesArg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Collector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Collector",
	HandlerType: (*CollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetKey",
			Handler:    _Collector_SetKey_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Collector_Ping_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _Collector_Kill_Handler,
		},
		{
			MethodName: "GetConfigPolicy",
			Handler:    _Collector_GetConfigPolicy_Handler,
		},
		{
			MethodName: "CollectMetrics",
			Handler:    _Collector_CollectMetrics_Handler,
		},
		{
			MethodName: "GetMetricTypes",
			Handler:    _Collector_GetMetricTypes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 874 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x96, 0x6d, 0x6f, 0xe3, 0x44,
	0x10, 0xc7, 0x2f, 0x71, 0x92, 0x8b, 0xc7, 0x79, 0xdc, 0x3b, 0x4e, 0xc6, 0xb4, 0xdc, 0xd5, 0x6f,
	0xe8, 0x63, 0x22, 0xb5, 0x08, 0xa1, 0x42, 0x2b, 0xe8, 0x13, 0xa0, 0xaa, 0x52, 0x95, 0xf2, 0xbe,
	0x4a, 0xdd, 0x6d, 0xb0, 0x70, 0x6c, 0x63, 0x3b, 0xd0, 0x20, 0xf1, 0x11, 0xf9, 0x00, 0x7c, 0x1a,
	0xd8, 0x9d, 0xb5, 0x9d, 0x5d, 0xc7, 0x86, 0x8a, 0x57, 0xa9, 0x67, 0x67, 0x7e, 0x3b, 0xff, 0x9d,
	0xd9, 0xd9, 0xc2, 0xf1, 0xcc, 0x4d, 0x7e, 0x5a, 0x3c, 0x8c, 0x9c, 0x60, 0x3e, 0x76, 0xfd, 0x84,
	0x7a, 0xf1, 0xa3, 0x7b, 0xf0, 0x3c, 0x8e, 0xfd, 0x69, 0x38, 0x76, 0x02, 0x3f, 0x89, 0x02, 0x6f,
	0x1c, 0x7a, 0x8b, 0x99, 0xeb, 0x8f, 0xa3, 0xd0, 0x49, 0xff, 0x1c, 0x85, 0x51, 0x90, 0x04, 0x44,
	0x63, 0x16, 0xeb, 0xe8, 0x5f, 0x00, 0x33, 0x1e, 0xc2, 0x16, 0xe6, 0x81, 0x9f, 0xfe, 0x88, 0x48,
	0xfb, 0xef, 0x1a, 0x34, 0x26, 0x0b, 0x8f, 0x92, 0x21, 0xe8, 0x11, 0xfb, 0xbd, 0x4f, 0x96, 0x21,
	0x35, 0x6b, 0x1f, 0x6a, 0xdb, 0x3a, 0x31, 0x40, 0xfb, 0x99, 0x2e, 0xcd, 0x3a, 0x7e, 0x0c, 0xa0,
	0x1d, 0xd1, 0x5f, 0x16, 0x6e, 0x44, 0x1f, 0x4d, 0x8d, 0x59, 0xda, 0xe4, 0x0d, 0x18, 0x94, 0xc6,
	0x4e, 0xe4, 0x86, 0x89, 0x1b, 0xf8, 0x66, 0x03, 0xdd, 0xde, 0x42, 0xe7, 0x21, 0x08, 0xbc, 0xfb,
	0x47, 0xfa, 0x34, 0x5d, 0x78, 0x89, 0xd9, 0x44, 0xd7, 0x8f, 0xa0, 0xfb, 0xe4, 0x05, 0xd3, 0x24,
	0x37, 0xb7, 0x98, 0xb9, 0xb6, 0x32, 0xcf, 0x5d, 0xdf, 0x9d, 0x2f, 0xe6, 0xe6, 0xeb, 0x82, 0x79,
	0xfa, 0x8c, 0xe6, 0x36, 0x9a, 0xd9, 0x7e, 0x4c, 0x56, 0x8e, 0xd0, 0x99, 0x51, 0xcb, 0x8c, 0x19,
	0x00, 0x14, 0x63, 0x1a, 0x6e, 0xa0, 0xf1, 0x1d, 0xf4, 0xe2, 0x24, 0x72, 0xfd, 0x59, 0x4e, 0xe8,
	0xf0, 0x8c, 0x6d, 0x13, 0xf4, 0x3b, 0x9a, 0x5c, 0xd3, 0xe5, 0xb7, 0xd1, 0x2c, 0x93, 0xcc, 0xf5,
	0x77, 0xec, 0x0d, 0x30, 0xc4, 0xca, 0x84, 0x86, 0xde, 0x92, 0x74, 0xa1, 0x49, 0xa3, 0x28, 0x88,
	0xc4, 0xe9, 0xd8, 0x16, 0xe8, 0xb7, 0x8c, 0x56, 0xba, 0xb6, 0x09, 0xc6, 0xb5, 0xeb, 0x79, 0x13,
	0x76, 0x60, 0x34, 0x4e, 0x48, 0x0f, 0x5a, 0x13, 0x3a, 0x8d, 0xd9, 0x21, 0xe5, 0xa1, 0x62, 0xb9,
	0x24, 0xf4, 0xcf, 0x06, 0xbc, 0xfd, 0x8e, 0x26, 0xe7, 0x81, 0xff, 0xe4, 0xce, 0x6e, 0x03, 0xcf,
	0x75, 0x4a, 0xb7, 0x27, 0xa7, 0x60, 0xe0, 0x41, 0x87, 0xe8, 0xc2, 0x8a, 0xa4, 0x6d, 0x1b, 0x87,
	0x3b, 0x23, 0x56, 0xe7, 0x51, 0x59, 0xf8, 0xe8, 0x8c, 0x39, 0x8b, 0xef, 0x4b, 0xd6, 0x4b, 0x4b,
	0xf2, 0x0d, 0x74, 0xc4, 0x21, 0xa7, 0x00, 0x0d, 0x01, 0xbb, 0xd5, 0x80, 0x2b, 0xee, 0x2d, 0x13,
	0x2e, 0xa0, 0xc7, 0xdb, 0x6c, 0x46, 0xa3, 0x8c, 0xd1, 0x40, 0xc6, 0x7e, 0x35, 0xe3, 0x07, 0xe1,
	0x2f, 0x53, 0xce, 0xa0, 0x9b, 0x96, 0x25, 0x85, 0x34, 0x11, 0xb2, 0x57, 0x0d, 0xb9, 0x43, 0x77,
	0x89, 0x61, 0x9d, 0x41, 0xbf, 0x28, 0x4f, 0x2a, 0xa4, 0x4e, 0x3e, 0x85, 0xe6, 0xaf, 0x53, 0x6f,
	0x41, 0xb1, 0x95, 0x8d, 0xc3, 0x3e, 0xb2, 0x57, 0x11, 0xc7, 0xf5, 0x2f, 0x6b, 0xd6, 0x05, 0x0c,
	0xd6, 0x14, 0x2a, 0x90, 0xf7, 0x2a, 0x64, 0x80, 0x10, 0x29, 0x04, 0x29, 0xdf, 0x03, 0x29, 0xd1,
	0xa8, 0x70, 0xb6, 0x54, 0x0e, 0x41, 0x8e, 0x12, 0x84, 0xa4, 0x2b, 0x18, 0xae, 0x09, 0x55, 0x41,
	0x1f, 0x54, 0xd0, 0x10, 0x41, 0x72, 0x0c, 0xe7, 0xd8, 0x07, 0xd0, 0xe6, 0x4a, 0xf1, 0x8e, 0xcb,
	0x77, 0xb8, 0x86, 0x17, 0xb3, 0x0f, 0xaf, 0xb3, 0xdb, 0xc0, 0x29, 0x6d, 0x3b, 0x01, 0x58, 0x1d,
	0x0c, 0xd9, 0x81, 0x26, 0x1f, 0x0a, 0x31, 0xf3, 0xe6, 0x45, 0xb1, 0x0a, 0x07, 0x37, 0xe2, 0xd4,
	0x58, 0xd4, 0xe0, 0x2b, 0x80, 0xd5, 0x97, 0x9a, 0xe8, 0x86, 0x9a, 0x68, 0x37, 0xa7, 0xf0, 0x00,
	0x4c, 0xf2, 0x16, 0x74, 0x3c, 0xc9, 0xea, 0x2c, 0xb3, 0x0b, 0x5e, 0xc7, 0x51, 0xc0, 0x0d, 0xe9,
	0xe5, 0xd6, 0x32, 0x43, 0xa6, 0x83, 0xcf, 0xa1, 0x9a, 0xfd, 0x1b, 0x18, 0x52, 0x6d, 0xc8, 0xae,
	0x2a, 0xe4, 0x93, 0x62, 0xf1, 0x64, 0x25, 0x5f, 0x57, 0x2b, 0xd9, 0x54, 0x95, 0xf4, 0x56, 0x98,
	0x5c, 0xca, 0x04, 0x8c, 0xb4, 0x98, 0x2f, 0x13, 0xa3, 0x15, 0xc5, 0x68, 0x45, 0x31, 0x9a, 0xfd,
	0x07, 0x74, 0x95, 0x06, 0x21, 0xfb, 0xaa, 0x9c, 0xcd, 0xf5, 0x1e, 0x92, 0x05, 0x9d, 0x56, 0x0b,
	0x2a, 0x6d, 0x6a, 0x29, 0x7f, 0x94, 0x34, 0x06, 0x10, 0x6d, 0xf5, 0xb2, 0x26, 0xd2, 0xed, 0xdf,
	0xa1, 0x23, 0xf7, 0x21, 0xd9, 0x53, 0xd3, 0xdd, 0x58, 0xeb, 0x54, 0x39, 0xdb, 0x93, 0xea, 0x6c,
	0x4b, 0xef, 0xf1, 0x2a, 0x35, 0x4c, 0xf6, 0x73, 0x18, 0x9e, 0x07, 0x9e, 0x47, 0x9d, 0xe4, 0x86,
	0xb2, 0x15, 0x27, 0xe6, 0x63, 0xfd, 0x3d, 0x3b, 0x62, 0xf1, 0x95, 0xa6, 0xd0, 0x1b, 0xa5, 0xaf,
	0xa0, 0x70, 0xb2, 0x2f, 0xe1, 0x8d, 0x1a, 0x25, 0x66, 0xee, 0x7f, 0xc5, 0xad, 0x86, 0xb2, 0x10,
	0xfe, 0x05, 0x0c, 0xd9, 0xc8, 0x12, 0x6b, 0x3f, 0xb2, 0x87, 0x14, 0x37, 0xdf, 0x82, 0x96, 0x83,
	0x43, 0x0c, 0x55, 0xf0, 0x8b, 0x9a, 0x32, 0xc4, 0x68, 0xbb, 0x99, 0x86, 0x7c, 0x7b, 0x35, 0xee,
	0x7f, 0x6d, 0x7f, 0xf8, 0x57, 0x1d, 0xf4, 0x54, 0x46, 0x10, 0xb1, 0x26, 0x69, 0x89, 0xe7, 0x8b,
	0x88, 0x3e, 0xcd, 0x5f, 0x39, 0x6b, 0x20, 0x7d, 0xe3, 0x4e, 0xf6, 0x2b, 0xf2, 0x19, 0x34, 0xf8,
	0x73, 0x46, 0xba, 0xd9, 0x16, 0x97, 0xf3, 0x30, 0x59, 0x5a, 0x22, 0x34, 0x7f, 0xe8, 0x98, 0xe3,
	0x2e, 0x34, 0xf8, 0xe3, 0x45, 0x04, 0x44, 0x7a, 0xe6, 0x52, 0xdf, 0xfc, 0x65, 0x63, 0xbe, 0x27,
	0xd0, 0x2f, 0x8c, 0xf0, 0x22, 0xff, 0xe3, 0xca, 0x39, 0xcf, 0xc2, 0xd9, 0x0b, 0xa3, 0x56, 0x85,
	0xbc, 0x43, 0xf7, 0xb5, 0x02, 0x5b, 0x66, 0x89, 0x5d, 0xa2, 0xa8, 0x87, 0x9b, 0x52, 0xd6, 0x2a,
	0x95, 0x52, 0x4a, 0x2a, 0x61, 0xbf, 0x7a, 0x68, 0xe1, 0xff, 0x4b, 0x47, 0xff, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x4f, 0xbe, 0xf6, 0x62, 0xa7, 0x09, 0x00, 0x00,
}
